rvm: 
  - 1.9.3
  - 1.9.2
# whitelist
branches:
  only:
    - master
# Needed for selenium browser
before_script: sh -e /etc/init.d/xvfb start

notifications:
  email:
    - cukes-devs@googlegroups.com
  irc:
    - "irc.freenode.org#cucumber"
